/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: 04be4daa9d2ed0ef9b96a37429c302bd)
interface __BaseEnv_CloudflareEnv {
	ASSETS: Fetcher;
	NEXT_PUBLIC_SITE_URL: "https://hgv-intelligence-site.ataaranyeokilo.workers.dev";
	NEXTJS_ENV: string;
	WORKER_SELF_REFERENCE: Service<typeof import("./.open-next/worker").default>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
